spring:
  application:
    name: transaction-service
  config:
    import: optional:configserver:http://localhost:9090
  profiles:
    active: native
  cloud:
    config:
      enabled: true
      uri: http://localhost:9090
      fail-fast: false

server:
  port: 9093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false