spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cool_bank
    username: postgres
    password: Lestitans@6
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:configserver:http://localhost:9090
  jpa:
    hibernate:
      ddl-auto: update # or 'update' for dev
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9094

#  data:
#    mongodb:
#      uri: mongodb+srv://kiptoo:<NRLD4fghDSkwwvnh>@cool-bank.h5juice.mongodb.net/
#      database: cool_bank

