spring:
  application:
    name: account-service
  profiles:
    active: ${PROFILE:default}

  # Config Server integration (with optional fallback)
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:9090}
  cloud:
    config:
      fail-fast: false
      retry:
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.5
        max-attempts: 3

  # Local fallback configuration (used if Config Server unavailable)

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cool_bank}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:Lestitans@6}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: ${JWT_SECRET:dev_default_secret}
    expiration-in-ms: 86400000 # 24 hours



  cloud:
    config:
      uri: http://localhost:9090  # Config Server URL
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.5
        max-attempts: 3