spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cool_bank
    username: postgres
    password: Lestitans@6
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


#app:
#  security:
#    jwt:
#      issuer: ${JWT_ISSUER:user-service}
#      secret: ${JWT_SECRET}
#      expiration-hours: 24