spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cool_bank
    username: postgres
    password: Lestitans@6
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true